DROP TABLE IF EXISTS ecom_order_items CASCADE;
DROP TABLE IF EXISTS ecom_orders CASCADE;
DROP TABLE IF EXISTS ecom_cart_items CASCADE;
DROP TABLE IF EXISTS ecom_carts CASCADE;
DROP TABLE IF EXISTS ecom_addresses CASCADE;
DROP TABLE IF EXISTS ecom_customers CASCADE;
DROP SEQUENCE IF EXISTS ecom_order_seq;
