-- ═══════════════════════════════════════════════════════════════
-- Exchange Module
-- An exchange is a combined credit note + new sale, processed
-- atomically. The original invoice is never modified.
-- ═══════════════════════════════════════════════════════════════

-- Main exchange header
CREATE TABLE exchange_orders (
    id                       UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    exchange_number          VARCHAR(50) NOT NULL UNIQUE,
    original_sales_invoice_id UUID NOT NULL REFERENCES sales_invoices(id),
    credit_note_id           UUID REFERENCES return_orders(id),        -- populated on complete
    new_sales_invoice_id     UUID REFERENCES sales_invoices(id),       -- populated on complete
    branch_id                UUID REFERENCES branches(id),
    warehouse_id             UUID REFERENCES warehouses(id),
    customer_id              UUID REFERENCES customers(id),
    status                   VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    items_out_total          DECIMAL(12,2) NOT NULL DEFAULT 0,
    items_in_total           DECIMAL(12,2) NOT NULL DEFAULT 0,
    net_amount               DECIMAL(12,2) NOT NULL DEFAULT 0,  -- positive = collect, negative = refund
    notes                    TEXT,
    created_by               UUID REFERENCES users(id),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at             TIMESTAMPTZ,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Items the customer is returning (drives the credit note)
CREATE TABLE exchange_items_out (
    id                    UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    exchange_order_id     UUID NOT NULL REFERENCES exchange_orders(id) ON DELETE CASCADE,
    sales_invoice_item_id UUID NOT NULL REFERENCES sales_invoice_items(id),
    variant_id            UUID NOT NULL REFERENCES variants(id),
    quantity              DECIMAL(10,2) NOT NULL,
    unit_price            DECIMAL(12,2) NOT NULL,
    discount              DECIMAL(12,2) NOT NULL DEFAULT 0,
    bill_discount_share   DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percent           DECIMAL(5,2)  NOT NULL DEFAULT 0,
    tax_amount            DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_price           DECIMAL(12,2) NOT NULL DEFAULT 0,
    reason                TEXT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Items the customer is taking (drives the new sales invoice)
CREATE TABLE exchange_items_in (
    id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    exchange_order_id UUID NOT NULL REFERENCES exchange_orders(id) ON DELETE CASCADE,
    variant_id        UUID NOT NULL REFERENCES variants(id),
    quantity          DECIMAL(10,2) NOT NULL,
    unit_price        DECIMAL(12,2) NOT NULL,
    discount          DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_percent       DECIMAL(5,2)  NOT NULL DEFAULT 0,
    tax_amount        DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_price       DECIMAL(12,2) NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Net cash movement for the exchange (difference between items_in and items_out)
CREATE TABLE exchange_settlements (
    id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    exchange_order_id UUID NOT NULL REFERENCES exchange_orders(id) ON DELETE CASCADE,
    amount            DECIMAL(12,2) NOT NULL,
    payment_method    VARCHAR(30) NOT NULL,
    direction         VARCHAR(10) NOT NULL CHECK (direction IN ('COLLECT', 'REFUND')),
    reference         VARCHAR(100),
    settled_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Tag return_orders rows that were generated by the exchange module so the
-- accounting recorder skips them (exchange is accounted via RecordExchange).
ALTER TABLE return_orders ADD COLUMN IF NOT EXISTS source VARCHAR(20) NOT NULL DEFAULT 'RETURN';

-- Indexes
CREATE INDEX idx_exchange_orders_original ON exchange_orders(original_sales_invoice_id);
CREATE INDEX idx_exchange_orders_customer  ON exchange_orders(customer_id);
CREATE INDEX idx_exchange_orders_branch    ON exchange_orders(branch_id);
CREATE INDEX idx_exchange_orders_status    ON exchange_orders(status);
CREATE INDEX idx_exchange_items_out_order  ON exchange_items_out(exchange_order_id);
CREATE INDEX idx_exchange_items_in_order   ON exchange_items_in(exchange_order_id);
CREATE INDEX idx_exchange_settlements_order ON exchange_settlements(exchange_order_id);
